Base (+bake) os packer
woyager/infra pull request #2
Opened 2017-09-05 17:01 UTC by woyager

2017-09-05 18:16 UTC, Artemmkin requested changes
Максим, привет! Извини, немного побуду занудой и попридераюсь :) 
Сначала по основному заданию:
1. В провиженере, который устанавливает монгу, ты указываешь, что запускать твой скрипт стоит с sudo, поэтому `sudo` в командах скрипта install_mongodb можно убрать, т.к. это кажется избыточным.
2. Описание образа должно быть более информативным и содержать инфу о дистрибутиве, установленном ПО, возможно, настройках, т.е. должно быть понятно их описания, что включает в себя образ. 
3. Из скрипта установки руби я бы убрал проверки `ruby -v`, `gem -v` они не несут смысловой нагрузки.

По заданию со звездочкой:
1. В билдере уже указывается пользователь для подключение по ssh  appuser. Поэтому в bake скрипте переключение appuser на самого себя выглядит странно. 
2. В результате билда immutable образа ожидалось, что при запуске инстанса из этого образа у нас уже будет рабоать приложение на инстансе. В твоем случае приложение приходится стартовать руками - это не Immutable подход :) 
В этом задании нужно сделать так, чтобы у тебя сервер пумы запускался при старте инстанса. Для этого можно написать, например,  [сервис файл](https://github.com/puma/puma/blob/master/docs/systemd.md) для пумы.

2017-09-06 15:54 UTC, Artemmkin commented
Привет, сейчас выглядит норм основная часть 👍 , поэтому апрувлю PR. 
immutable имидж не билдится, у тебя ошибки в `bake.sh` скрипте. Рекомендую использовать команду `set -e` в начале скрипта, чтобы ошибки не проходили незамеченными. 
И еще просьба писать в комментариях PR, что твои наработки готовы и их можно посмотреть, а то я не знаю,  можно ли еще смотреть или нет :)

2017-09-06 15:54 UTC, Artemmkin approved these changes

2017-09-06 18:25 UTC, woyager commented
Привет. Я тут немного приболел, потому не доделал immutable ( Как поправлюсь/доделаю - отпишусь.
За критику спасибо - ради обратной связи мы тут все и делаем )

2017-09-06 20:16 UTC, Artemmkin commented
Поправляйся! 
Отношение к замечанием правильное 👍

2017-09-08 13:39 UTC, woyager commented
Привет.

Переделал создание immutable образа. Что было сделано/исправлено
1. Вместо скрипта bake.sh, в котором делалась вся работа - последовательность provisioners. Так нагляднее и логичней.
2. Ошибка с деплоем reddit заключалась в отсутствии source
3. Autostart puma "делался" из под appuser без sudo, что приводило ... ни к чему )

На текущем коммите все деплоится, образ собирается, если создасть с него VM - приложение работает.

2017-09-08 14:53 UTC, Artemmkin commented
Отлично 👍 мерджи и переходи к следующему заданию

2017-09-08 14:59 UTC, merged